FROM ubuntu:18.04
LABEL name="Java_8"
LABEL maintainer="j.ajaynaidu@gmail.com"

RUN apt-get update && apt-get install -y openjdk-8-jdk \
 && apt-get clean && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
 && mkdir /app

WORKDIR /app/
CMD ["/app/script.sh"]