FROM ubuntu:18.04
LABEL maintainer="j.ajaynaidu@gmail.com"

RUN apt-get update && apt-get install --no-install-recommends -y wget unzip openjdk-8-jdk \
 && apt-get clean \
 && wget --no-check-certificate https://services.gradle.org/distributions/gradle-5.5.1-bin.zip \
 && unzip gradle-5.5.1-bin.zip \
 && rm gradle-5.5.1-bin.zip \
 && mv gradle-5.5.1 /usr/local/ \
 && ln -s /usr/local/gradle-5.5.1/bin/gradle /usr/bin/gradle \
 && mkdir /app

WORKDIR /app/
CMD ["/app/script.sh"]