FROM ubuntu:16.04
LABEL maintainer="j.ajaynaidu@gmail.com"

RUN apt-get -qq update && apt-get -qq install wget \
 && apt-get install python -y && apt-get clean \
 && wget https://nodejs.org/dist/v12.16.1/node-v12.16.1-linux-x64.tar.gz \
 && tar -xvf node-v12.16.1-linux-x64.tar.gz \
 && rm node-v12.16.1-linux-x64.tar.gz \
 && mv node-v12.16.1-linux-x64 /usr/local/ \
 && ln -s /usr/local/node-v12.16.1-linux-x64/bin/node /usr/bin/node \
 && ln -s /usr/local/node-v12.16.1-linux-x64/bin/npm /usr/bin/npm \